language: rust
os: osx
rust: stable
env: TARGET=x86_64-apple-darwin
cache: cargo

script:
  - cargo test --all

before_deploy:
  - cargo build --target $TARGET --release
  - mkdir "esa-nippou_${TRAVIS_TAG}_${TARGET}"
  - cp target/$TARGET/release/esa-nippou LICENSE README.md "esa-nippou_${TRAVIS_TAG}_${TARGET}"
  - zip "esa-nippou_${TRAVIS_TAG}_${TARGET}.zip" -r "esa-nippou_${TRAVIS_TAG}_${TARGET}"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: esa-nippou_${TRAVIS_TAG}_${TARGET}.zip
  skip_cleanup: true
  on:
    repo: mizukmb/esa-nippou
    tags: true
