name: Rust

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Cargo
      run: which cargo > /dev/null 2>&1 || curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Run test
      run: cargo test --verbose
