name: Rust

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Run test on OS: ${{ matrix.os }}
      run: cargo test --verbose
